server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://192.168.157.181:3306/security_flow_assert
#    url: jdbc:mysql://127.0.0.1:3306/security_flow_assert
    username: root
    password: root
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true