spring:
  datasource:
    url: jdbc:mysql://192.168.157.181:3306/security_flow_assert
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



  main:
    allow-circular-references: true
    web-application-type: none